// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import TransactionController from './transaction_controller'
application.register('transaction', TransactionController)
